# Generated by Django 4.2.6 on 2023-11-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
